/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackOrderRouteImport } from './routes/track-order'
import { Route as SustainabilityRouteImport } from './routes/sustainability'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as NewsRouteImport } from './routes/news'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InvestorsRouteImport } from './routes/investors'
import { Route as InnovationRouteImport } from './routes/innovation'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as FutureRouteImport } from './routes/future'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CompaniesRouteImport } from './routes/companies'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as AuthenticatedTicketsRouteImport } from './routes/_authenticated/tickets'
import { Route as AuthenticatedCheckoutRouteImport } from './routes/_authenticated/checkout'
import { Route as AuthenticatedOrdersIndexRouteImport } from './routes/_authenticated/orders.index'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin/admin.index'
import { Route as AuthenticatedTicketsIdRouteImport } from './routes/_authenticated/tickets.$id'
import { Route as AuthenticatedOrdersIdRouteImport } from './routes/_authenticated/orders.$id'
import { Route as AuthenticatedCheckoutSuccessRouteImport } from './routes/_authenticated/checkout.success'
import { Route as AuthenticatedCheckoutCancelRouteImport } from './routes/_authenticated/checkout.cancel'
import { Route as AdminAdminTicketsRouteImport } from './routes/_admin/admin.tickets'
import { Route as AdminAdminProductsRouteImport } from './routes/_admin/admin.products'
import { Route as AdminAdminOrdersRouteImport } from './routes/_admin/admin.orders'
import { Route as AdminAdminBranchesRouteImport } from './routes/_admin/admin.branches'
import { Route as ApiPublicWebhooksMpesaRouteImport } from './routes/api/public/webhooks/mpesa'
import { Route as AdminAdminSystemCategoryRouteImport } from './routes/_admin/admin.system.$category'
import { Route as AdminAdminReportsSubRouteImport } from './routes/_admin/admin.reports.$sub'
import { Route as AdminAdminCustomersCategoryRouteImport } from './routes/_admin/admin.customers.$category'
import { Route as AdminAdminCommerceCategoryRouteImport } from './routes/_admin/admin.commerce.$category'
import { Route as AdminAdminAnalyticsSubRouteImport } from './routes/_admin/admin.analytics.$sub'
import { Route as AdminAdminSystemCategorySubRouteImport } from './routes/_admin/admin.system.$category.$sub'
import { Route as AdminAdminGrowthCategorySubRouteImport } from './routes/_admin/admin.growth.$category.$sub'
import { Route as AdminAdminCustomersCategorySubRouteImport } from './routes/_admin/admin.customers.$category.$sub'
import { Route as AdminAdminCommerceCategorySubRouteImport } from './routes/_admin/admin.commerce.$category.$sub'

const TrackOrderRoute = TrackOrderRouteImport.update({
  id: '/track-order',
  path: '/track-order',
  getParentRoute: () => rootRouteImport,
} as any)
const SustainabilityRoute = SustainabilityRouteImport.update({
  id: '/sustainability',
  path: '/sustainability',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestorsRoute = InvestorsRouteImport.update({
  id: '/investors',
  path: '/investors',
  getParentRoute: () => rootRouteImport,
} as any)
const InnovationRoute = InnovationRouteImport.update({
  id: '/innovation',
  path: '/innovation',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const FutureRoute = FutureRouteImport.update({
  id: '/future',
  path: '/future',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesRoute = CompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTicketsRoute = AuthenticatedTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCheckoutRoute = AuthenticatedCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOrdersIndexRoute =
  AuthenticatedOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdminRoute,
} as any)
const AuthenticatedTicketsIdRoute = AuthenticatedTicketsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedTicketsRoute,
} as any)
const AuthenticatedOrdersIdRoute = AuthenticatedOrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCheckoutSuccessRoute =
  AuthenticatedCheckoutSuccessRouteImport.update({
    id: '/success',
    path: '/success',
    getParentRoute: () => AuthenticatedCheckoutRoute,
  } as any)
const AuthenticatedCheckoutCancelRoute =
  AuthenticatedCheckoutCancelRouteImport.update({
    id: '/cancel',
    path: '/cancel',
    getParentRoute: () => AuthenticatedCheckoutRoute,
  } as any)
const AdminAdminTicketsRoute = AdminAdminTicketsRouteImport.update({
  id: '/admin/tickets',
  path: '/admin/tickets',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminProductsRoute = AdminAdminProductsRouteImport.update({
  id: '/admin/products',
  path: '/admin/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminOrdersRoute = AdminAdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminBranchesRoute = AdminAdminBranchesRouteImport.update({
  id: '/admin/branches',
  path: '/admin/branches',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicWebhooksMpesaRoute = ApiPublicWebhooksMpesaRouteImport.update({
  id: '/api/public/webhooks/mpesa',
  path: '/api/public/webhooks/mpesa',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminSystemCategoryRoute =
  AdminAdminSystemCategoryRouteImport.update({
    id: '/admin/system/$category',
    path: '/admin/system/$category',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAdminReportsSubRoute = AdminAdminReportsSubRouteImport.update({
  id: '/admin/reports/$sub',
  path: '/admin/reports/$sub',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminCustomersCategoryRoute =
  AdminAdminCustomersCategoryRouteImport.update({
    id: '/admin/customers/$category',
    path: '/admin/customers/$category',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAdminCommerceCategoryRoute =
  AdminAdminCommerceCategoryRouteImport.update({
    id: '/admin/commerce/$category',
    path: '/admin/commerce/$category',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAdminAnalyticsSubRoute = AdminAdminAnalyticsSubRouteImport.update({
  id: '/admin/analytics/$sub',
  path: '/admin/analytics/$sub',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminSystemCategorySubRoute =
  AdminAdminSystemCategorySubRouteImport.update({
    id: '/$sub',
    path: '/$sub',
    getParentRoute: () => AdminAdminSystemCategoryRoute,
  } as any)
const AdminAdminGrowthCategorySubRoute =
  AdminAdminGrowthCategorySubRouteImport.update({
    id: '/admin/growth/$category/$sub',
    path: '/admin/growth/$category/$sub',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAdminCustomersCategorySubRoute =
  AdminAdminCustomersCategorySubRouteImport.update({
    id: '/$sub',
    path: '/$sub',
    getParentRoute: () => AdminAdminCustomersCategoryRoute,
  } as any)
const AdminAdminCommerceCategorySubRoute =
  AdminAdminCommerceCategorySubRouteImport.update({
    id: '/$sub',
    path: '/$sub',
    getParentRoute: () => AdminAdminCommerceCategoryRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/companies': typeof CompaniesRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/future': typeof FutureRoute
  '/industries': typeof IndustriesRoute
  '/innovation': typeof InnovationRoute
  '/investors': typeof InvestorsRoute
  '/login': typeof LoginRoute
  '/news': typeof NewsRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/shop': typeof ShopRoute
  '/sustainability': typeof SustainabilityRoute
  '/track-order': typeof TrackOrderRoute
  '/checkout': typeof AuthenticatedCheckoutRouteWithChildren
  '/tickets': typeof AuthenticatedTicketsRouteWithChildren
  '/product/$slug': typeof ProductSlugRoute
  '/admin/branches': typeof AdminAdminBranchesRoute
  '/admin/orders': typeof AdminAdminOrdersRoute
  '/admin/products': typeof AdminAdminProductsRoute
  '/admin/tickets': typeof AdminAdminTicketsRoute
  '/checkout/cancel': typeof AuthenticatedCheckoutCancelRoute
  '/checkout/success': typeof AuthenticatedCheckoutSuccessRoute
  '/orders/$id': typeof AuthenticatedOrdersIdRoute
  '/tickets/$id': typeof AuthenticatedTicketsIdRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/orders/': typeof AuthenticatedOrdersIndexRoute
  '/admin/analytics/$sub': typeof AdminAdminAnalyticsSubRoute
  '/admin/commerce/$category': typeof AdminAdminCommerceCategoryRouteWithChildren
  '/admin/customers/$category': typeof AdminAdminCustomersCategoryRouteWithChildren
  '/admin/reports/$sub': typeof AdminAdminReportsSubRoute
  '/admin/system/$category': typeof AdminAdminSystemCategoryRouteWithChildren
  '/api/public/webhooks/mpesa': typeof ApiPublicWebhooksMpesaRoute
  '/admin/commerce/$category/$sub': typeof AdminAdminCommerceCategorySubRoute
  '/admin/customers/$category/$sub': typeof AdminAdminCustomersCategorySubRoute
  '/admin/growth/$category/$sub': typeof AdminAdminGrowthCategorySubRoute
  '/admin/system/$category/$sub': typeof AdminAdminSystemCategorySubRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/companies': typeof CompaniesRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/future': typeof FutureRoute
  '/industries': typeof IndustriesRoute
  '/innovation': typeof InnovationRoute
  '/investors': typeof InvestorsRoute
  '/login': typeof LoginRoute
  '/news': typeof NewsRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/shop': typeof ShopRoute
  '/sustainability': typeof SustainabilityRoute
  '/track-order': typeof TrackOrderRoute
  '/checkout': typeof AuthenticatedCheckoutRouteWithChildren
  '/tickets': typeof AuthenticatedTicketsRouteWithChildren
  '/product/$slug': typeof ProductSlugRoute
  '/admin/branches': typeof AdminAdminBranchesRoute
  '/admin/orders': typeof AdminAdminOrdersRoute
  '/admin/products': typeof AdminAdminProductsRoute
  '/admin/tickets': typeof AdminAdminTicketsRoute
  '/checkout/cancel': typeof AuthenticatedCheckoutCancelRoute
  '/checkout/success': typeof AuthenticatedCheckoutSuccessRoute
  '/orders/$id': typeof AuthenticatedOrdersIdRoute
  '/tickets/$id': typeof AuthenticatedTicketsIdRoute
  '/admin': typeof AdminAdminIndexRoute
  '/orders': typeof AuthenticatedOrdersIndexRoute
  '/admin/analytics/$sub': typeof AdminAdminAnalyticsSubRoute
  '/admin/commerce/$category': typeof AdminAdminCommerceCategoryRouteWithChildren
  '/admin/customers/$category': typeof AdminAdminCustomersCategoryRouteWithChildren
  '/admin/reports/$sub': typeof AdminAdminReportsSubRoute
  '/admin/system/$category': typeof AdminAdminSystemCategoryRouteWithChildren
  '/api/public/webhooks/mpesa': typeof ApiPublicWebhooksMpesaRoute
  '/admin/commerce/$category/$sub': typeof AdminAdminCommerceCategorySubRoute
  '/admin/customers/$category/$sub': typeof AdminAdminCustomersCategorySubRoute
  '/admin/growth/$category/$sub': typeof AdminAdminGrowthCategorySubRoute
  '/admin/system/$category/$sub': typeof AdminAdminSystemCategorySubRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/companies': typeof CompaniesRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/future': typeof FutureRoute
  '/industries': typeof IndustriesRoute
  '/innovation': typeof InnovationRoute
  '/investors': typeof InvestorsRoute
  '/login': typeof LoginRoute
  '/news': typeof NewsRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/shop': typeof ShopRoute
  '/sustainability': typeof SustainabilityRoute
  '/track-order': typeof TrackOrderRoute
  '/_authenticated/checkout': typeof AuthenticatedCheckoutRouteWithChildren
  '/_authenticated/tickets': typeof AuthenticatedTicketsRouteWithChildren
  '/product/$slug': typeof ProductSlugRoute
  '/_admin/admin/branches': typeof AdminAdminBranchesRoute
  '/_admin/admin/orders': typeof AdminAdminOrdersRoute
  '/_admin/admin/products': typeof AdminAdminProductsRoute
  '/_admin/admin/tickets': typeof AdminAdminTicketsRoute
  '/_authenticated/checkout/cancel': typeof AuthenticatedCheckoutCancelRoute
  '/_authenticated/checkout/success': typeof AuthenticatedCheckoutSuccessRoute
  '/_authenticated/orders/$id': typeof AuthenticatedOrdersIdRoute
  '/_authenticated/tickets/$id': typeof AuthenticatedTicketsIdRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/_authenticated/orders/': typeof AuthenticatedOrdersIndexRoute
  '/_admin/admin/analytics/$sub': typeof AdminAdminAnalyticsSubRoute
  '/_admin/admin/commerce/$category': typeof AdminAdminCommerceCategoryRouteWithChildren
  '/_admin/admin/customers/$category': typeof AdminAdminCustomersCategoryRouteWithChildren
  '/_admin/admin/reports/$sub': typeof AdminAdminReportsSubRoute
  '/_admin/admin/system/$category': typeof AdminAdminSystemCategoryRouteWithChildren
  '/api/public/webhooks/mpesa': typeof ApiPublicWebhooksMpesaRoute
  '/_admin/admin/commerce/$category/$sub': typeof AdminAdminCommerceCategorySubRoute
  '/_admin/admin/customers/$category/$sub': typeof AdminAdminCustomersCategorySubRoute
  '/_admin/admin/growth/$category/$sub': typeof AdminAdminGrowthCategorySubRoute
  '/_admin/admin/system/$category/$sub': typeof AdminAdminSystemCategorySubRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/careers'
    | '/companies'
    | '/contact'
    | '/forgot-password'
    | '/future'
    | '/industries'
    | '/innovation'
    | '/investors'
    | '/login'
    | '/news'
    | '/register'
    | '/reset-password'
    | '/shop'
    | '/sustainability'
    | '/track-order'
    | '/checkout'
    | '/tickets'
    | '/product/$slug'
    | '/admin/branches'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/tickets'
    | '/checkout/cancel'
    | '/checkout/success'
    | '/orders/$id'
    | '/tickets/$id'
    | '/admin/'
    | '/orders/'
    | '/admin/analytics/$sub'
    | '/admin/commerce/$category'
    | '/admin/customers/$category'
    | '/admin/reports/$sub'
    | '/admin/system/$category'
    | '/api/public/webhooks/mpesa'
    | '/admin/commerce/$category/$sub'
    | '/admin/customers/$category/$sub'
    | '/admin/growth/$category/$sub'
    | '/admin/system/$category/$sub'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/careers'
    | '/companies'
    | '/contact'
    | '/forgot-password'
    | '/future'
    | '/industries'
    | '/innovation'
    | '/investors'
    | '/login'
    | '/news'
    | '/register'
    | '/reset-password'
    | '/shop'
    | '/sustainability'
    | '/track-order'
    | '/checkout'
    | '/tickets'
    | '/product/$slug'
    | '/admin/branches'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/tickets'
    | '/checkout/cancel'
    | '/checkout/success'
    | '/orders/$id'
    | '/tickets/$id'
    | '/admin'
    | '/orders'
    | '/admin/analytics/$sub'
    | '/admin/commerce/$category'
    | '/admin/customers/$category'
    | '/admin/reports/$sub'
    | '/admin/system/$category'
    | '/api/public/webhooks/mpesa'
    | '/admin/commerce/$category/$sub'
    | '/admin/customers/$category/$sub'
    | '/admin/growth/$category/$sub'
    | '/admin/system/$category/$sub'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_authenticated'
    | '/about'
    | '/careers'
    | '/companies'
    | '/contact'
    | '/forgot-password'
    | '/future'
    | '/industries'
    | '/innovation'
    | '/investors'
    | '/login'
    | '/news'
    | '/register'
    | '/reset-password'
    | '/shop'
    | '/sustainability'
    | '/track-order'
    | '/_authenticated/checkout'
    | '/_authenticated/tickets'
    | '/product/$slug'
    | '/_admin/admin/branches'
    | '/_admin/admin/orders'
    | '/_admin/admin/products'
    | '/_admin/admin/tickets'
    | '/_authenticated/checkout/cancel'
    | '/_authenticated/checkout/success'
    | '/_authenticated/orders/$id'
    | '/_authenticated/tickets/$id'
    | '/_admin/admin/'
    | '/_authenticated/orders/'
    | '/_admin/admin/analytics/$sub'
    | '/_admin/admin/commerce/$category'
    | '/_admin/admin/customers/$category'
    | '/_admin/admin/reports/$sub'
    | '/_admin/admin/system/$category'
    | '/api/public/webhooks/mpesa'
    | '/_admin/admin/commerce/$category/$sub'
    | '/_admin/admin/customers/$category/$sub'
    | '/_admin/admin/growth/$category/$sub'
    | '/_admin/admin/system/$category/$sub'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  CareersRoute: typeof CareersRoute
  CompaniesRoute: typeof CompaniesRoute
  ContactRoute: typeof ContactRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  FutureRoute: typeof FutureRoute
  IndustriesRoute: typeof IndustriesRoute
  InnovationRoute: typeof InnovationRoute
  InvestorsRoute: typeof InvestorsRoute
  LoginRoute: typeof LoginRoute
  NewsRoute: typeof NewsRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ShopRoute: typeof ShopRoute
  SustainabilityRoute: typeof SustainabilityRoute
  TrackOrderRoute: typeof TrackOrderRoute
  ProductSlugRoute: typeof ProductSlugRoute
  ApiPublicWebhooksMpesaRoute: typeof ApiPublicWebhooksMpesaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/track-order': {
      id: '/track-order'
      path: '/track-order'
      fullPath: '/track-order'
      preLoaderRoute: typeof TrackOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sustainability': {
      id: '/sustainability'
      path: '/sustainability'
      fullPath: '/sustainability'
      preLoaderRoute: typeof SustainabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investors': {
      id: '/investors'
      path: '/investors'
      fullPath: '/investors'
      preLoaderRoute: typeof InvestorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/innovation': {
      id: '/innovation'
      path: '/innovation'
      fullPath: '/innovation'
      preLoaderRoute: typeof InnovationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/future': {
      id: '/future'
      path: '/future'
      fullPath: '/future'
      preLoaderRoute: typeof FutureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies': {
      id: '/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof CompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tickets': {
      id: '/_authenticated/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof AuthenticatedTicketsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/checkout': {
      id: '/_authenticated/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof AuthenticatedCheckoutRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orders/': {
      id: '/_authenticated/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof AuthenticatedOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/tickets/$id': {
      id: '/_authenticated/tickets/$id'
      path: '/$id'
      fullPath: '/tickets/$id'
      preLoaderRoute: typeof AuthenticatedTicketsIdRouteImport
      parentRoute: typeof AuthenticatedTicketsRoute
    }
    '/_authenticated/orders/$id': {
      id: '/_authenticated/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof AuthenticatedOrdersIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/checkout/success': {
      id: '/_authenticated/checkout/success'
      path: '/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof AuthenticatedCheckoutSuccessRouteImport
      parentRoute: typeof AuthenticatedCheckoutRoute
    }
    '/_authenticated/checkout/cancel': {
      id: '/_authenticated/checkout/cancel'
      path: '/cancel'
      fullPath: '/checkout/cancel'
      preLoaderRoute: typeof AuthenticatedCheckoutCancelRouteImport
      parentRoute: typeof AuthenticatedCheckoutRoute
    }
    '/_admin/admin/tickets': {
      id: '/_admin/admin/tickets'
      path: '/admin/tickets'
      fullPath: '/admin/tickets'
      preLoaderRoute: typeof AdminAdminTicketsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/products': {
      id: '/_admin/admin/products'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminAdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/orders': {
      id: '/_admin/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminAdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/branches': {
      id: '/_admin/admin/branches'
      path: '/admin/branches'
      fullPath: '/admin/branches'
      preLoaderRoute: typeof AdminAdminBranchesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/webhooks/mpesa': {
      id: '/api/public/webhooks/mpesa'
      path: '/api/public/webhooks/mpesa'
      fullPath: '/api/public/webhooks/mpesa'
      preLoaderRoute: typeof ApiPublicWebhooksMpesaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/admin/system/$category': {
      id: '/_admin/admin/system/$category'
      path: '/admin/system/$category'
      fullPath: '/admin/system/$category'
      preLoaderRoute: typeof AdminAdminSystemCategoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/reports/$sub': {
      id: '/_admin/admin/reports/$sub'
      path: '/admin/reports/$sub'
      fullPath: '/admin/reports/$sub'
      preLoaderRoute: typeof AdminAdminReportsSubRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/customers/$category': {
      id: '/_admin/admin/customers/$category'
      path: '/admin/customers/$category'
      fullPath: '/admin/customers/$category'
      preLoaderRoute: typeof AdminAdminCustomersCategoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/commerce/$category': {
      id: '/_admin/admin/commerce/$category'
      path: '/admin/commerce/$category'
      fullPath: '/admin/commerce/$category'
      preLoaderRoute: typeof AdminAdminCommerceCategoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/analytics/$sub': {
      id: '/_admin/admin/analytics/$sub'
      path: '/admin/analytics/$sub'
      fullPath: '/admin/analytics/$sub'
      preLoaderRoute: typeof AdminAdminAnalyticsSubRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/system/$category/$sub': {
      id: '/_admin/admin/system/$category/$sub'
      path: '/$sub'
      fullPath: '/admin/system/$category/$sub'
      preLoaderRoute: typeof AdminAdminSystemCategorySubRouteImport
      parentRoute: typeof AdminAdminSystemCategoryRoute
    }
    '/_admin/admin/growth/$category/$sub': {
      id: '/_admin/admin/growth/$category/$sub'
      path: '/admin/growth/$category/$sub'
      fullPath: '/admin/growth/$category/$sub'
      preLoaderRoute: typeof AdminAdminGrowthCategorySubRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/customers/$category/$sub': {
      id: '/_admin/admin/customers/$category/$sub'
      path: '/$sub'
      fullPath: '/admin/customers/$category/$sub'
      preLoaderRoute: typeof AdminAdminCustomersCategorySubRouteImport
      parentRoute: typeof AdminAdminCustomersCategoryRoute
    }
    '/_admin/admin/commerce/$category/$sub': {
      id: '/_admin/admin/commerce/$category/$sub'
      path: '/$sub'
      fullPath: '/admin/commerce/$category/$sub'
      preLoaderRoute: typeof AdminAdminCommerceCategorySubRouteImport
      parentRoute: typeof AdminAdminCommerceCategoryRoute
    }
  }
}

interface AdminAdminCommerceCategoryRouteChildren {
  AdminAdminCommerceCategorySubRoute: typeof AdminAdminCommerceCategorySubRoute
}

const AdminAdminCommerceCategoryRouteChildren: AdminAdminCommerceCategoryRouteChildren =
  {
    AdminAdminCommerceCategorySubRoute: AdminAdminCommerceCategorySubRoute,
  }

const AdminAdminCommerceCategoryRouteWithChildren =
  AdminAdminCommerceCategoryRoute._addFileChildren(
    AdminAdminCommerceCategoryRouteChildren,
  )

interface AdminAdminCustomersCategoryRouteChildren {
  AdminAdminCustomersCategorySubRoute: typeof AdminAdminCustomersCategorySubRoute
}

const AdminAdminCustomersCategoryRouteChildren: AdminAdminCustomersCategoryRouteChildren =
  {
    AdminAdminCustomersCategorySubRoute: AdminAdminCustomersCategorySubRoute,
  }

const AdminAdminCustomersCategoryRouteWithChildren =
  AdminAdminCustomersCategoryRoute._addFileChildren(
    AdminAdminCustomersCategoryRouteChildren,
  )

interface AdminAdminSystemCategoryRouteChildren {
  AdminAdminSystemCategorySubRoute: typeof AdminAdminSystemCategorySubRoute
}

const AdminAdminSystemCategoryRouteChildren: AdminAdminSystemCategoryRouteChildren =
  {
    AdminAdminSystemCategorySubRoute: AdminAdminSystemCategorySubRoute,
  }

const AdminAdminSystemCategoryRouteWithChildren =
  AdminAdminSystemCategoryRoute._addFileChildren(
    AdminAdminSystemCategoryRouteChildren,
  )

interface AdminRouteChildren {
  AdminAdminBranchesRoute: typeof AdminAdminBranchesRoute
  AdminAdminOrdersRoute: typeof AdminAdminOrdersRoute
  AdminAdminProductsRoute: typeof AdminAdminProductsRoute
  AdminAdminTicketsRoute: typeof AdminAdminTicketsRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
  AdminAdminAnalyticsSubRoute: typeof AdminAdminAnalyticsSubRoute
  AdminAdminCommerceCategoryRoute: typeof AdminAdminCommerceCategoryRouteWithChildren
  AdminAdminCustomersCategoryRoute: typeof AdminAdminCustomersCategoryRouteWithChildren
  AdminAdminReportsSubRoute: typeof AdminAdminReportsSubRoute
  AdminAdminSystemCategoryRoute: typeof AdminAdminSystemCategoryRouteWithChildren
  AdminAdminGrowthCategorySubRoute: typeof AdminAdminGrowthCategorySubRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminBranchesRoute: AdminAdminBranchesRoute,
  AdminAdminOrdersRoute: AdminAdminOrdersRoute,
  AdminAdminProductsRoute: AdminAdminProductsRoute,
  AdminAdminTicketsRoute: AdminAdminTicketsRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
  AdminAdminAnalyticsSubRoute: AdminAdminAnalyticsSubRoute,
  AdminAdminCommerceCategoryRoute: AdminAdminCommerceCategoryRouteWithChildren,
  AdminAdminCustomersCategoryRoute:
    AdminAdminCustomersCategoryRouteWithChildren,
  AdminAdminReportsSubRoute: AdminAdminReportsSubRoute,
  AdminAdminSystemCategoryRoute: AdminAdminSystemCategoryRouteWithChildren,
  AdminAdminGrowthCategorySubRoute: AdminAdminGrowthCategorySubRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthenticatedCheckoutRouteChildren {
  AuthenticatedCheckoutCancelRoute: typeof AuthenticatedCheckoutCancelRoute
  AuthenticatedCheckoutSuccessRoute: typeof AuthenticatedCheckoutSuccessRoute
}

const AuthenticatedCheckoutRouteChildren: AuthenticatedCheckoutRouteChildren = {
  AuthenticatedCheckoutCancelRoute: AuthenticatedCheckoutCancelRoute,
  AuthenticatedCheckoutSuccessRoute: AuthenticatedCheckoutSuccessRoute,
}

const AuthenticatedCheckoutRouteWithChildren =
  AuthenticatedCheckoutRoute._addFileChildren(
    AuthenticatedCheckoutRouteChildren,
  )

interface AuthenticatedTicketsRouteChildren {
  AuthenticatedTicketsIdRoute: typeof AuthenticatedTicketsIdRoute
}

const AuthenticatedTicketsRouteChildren: AuthenticatedTicketsRouteChildren = {
  AuthenticatedTicketsIdRoute: AuthenticatedTicketsIdRoute,
}

const AuthenticatedTicketsRouteWithChildren =
  AuthenticatedTicketsRoute._addFileChildren(AuthenticatedTicketsRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedCheckoutRoute: typeof AuthenticatedCheckoutRouteWithChildren
  AuthenticatedTicketsRoute: typeof AuthenticatedTicketsRouteWithChildren
  AuthenticatedOrdersIdRoute: typeof AuthenticatedOrdersIdRoute
  AuthenticatedOrdersIndexRoute: typeof AuthenticatedOrdersIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCheckoutRoute: AuthenticatedCheckoutRouteWithChildren,
  AuthenticatedTicketsRoute: AuthenticatedTicketsRouteWithChildren,
  AuthenticatedOrdersIdRoute: AuthenticatedOrdersIdRoute,
  AuthenticatedOrdersIndexRoute: AuthenticatedOrdersIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  CareersRoute: CareersRoute,
  CompaniesRoute: CompaniesRoute,
  ContactRoute: ContactRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  FutureRoute: FutureRoute,
  IndustriesRoute: IndustriesRoute,
  InnovationRoute: InnovationRoute,
  InvestorsRoute: InvestorsRoute,
  LoginRoute: LoginRoute,
  NewsRoute: NewsRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ShopRoute: ShopRoute,
  SustainabilityRoute: SustainabilityRoute,
  TrackOrderRoute: TrackOrderRoute,
  ProductSlugRoute: ProductSlugRoute,
  ApiPublicWebhooksMpesaRoute: ApiPublicWebhooksMpesaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
